"""
Render Supplementary Table S5 (pre-registered sensitivity analyses SA2-SA5)
from the outputs of scripts/sa2_sa5_sensitivity.py.

Outputs:
  manuscript/table_s5_sa2_sa5.md
"""

from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
RESULTS_DIR = PROJECT_ROOT / "results"
MANUSCRIPT_DIR = PROJECT_ROOT / "manuscript"


def main():
    sa2 = pd.read_csv(RESULTS_DIR / "sa2_concordance_matrix.csv")
    long = pd.read_csv(RESULTS_DIR / "sa2_sa5_sensitivity.csv")

    sa2 = sa2.assign(Site=lambda d: d["gene"] + "-" + d["aa_position"].astype(str))
    panel_a = sa2[[
        "Site", "denominator", "n_primary", "n_both", "n_ivar_only",
        "n_lofreq_only", "prev_primary_pct", "prev_ivar_alone_pct",
        "prev_lofreq_alone_pct",
    ]].rename(columns={
        "denominator": "Denominator",
        "n_primary": "Concordant (primary)",
        "n_both": "Both callers (own thresholds)",
        "n_ivar_only": "iVar only",
        "n_lofreq_only": "LoFreq only",
        "prev_primary_pct": "Prevalence, primary (%)",
        "prev_ivar_alone_pct": "Prevalence, iVar alone (%)",
        "prev_lofreq_alone_pct": "Prevalence, LoFreq alone (%)",
    }).round(3)

    def wide(analysis):
        g = long[long["analysis"] == analysis]
        det = g.pivot_table(index="label", columns="stratum",
                            values="detections", sort=False).astype(int)
        den = g.groupby("stratum")["denominator"].max().to_dict()
        det.columns = [f"{c} (n={den[c]:,})" for c in det.columns]
        return det.reset_index().rename(columns={"label": "Site"})

    md = [
        "# Supplementary Table S5. Pre-registered sensitivity analyses SA2–SA5",
        "",
        "Generated by `scripts/sa2_sa5_sensitivity.py` and rendered by "
        "`scripts/build_table_s5.py`. All panels use the 3% operational allele-frequency "
        "threshold and the corrected strand-bias filter.",
        "",
        "## Panel A. SA2 — single-caller analysis and caller-concordance matrix",
        "",
        "Two distinct notions of concordance are reported and should not be conflated. "
        "\"Concordant (primary)\" reproduces the primary analysis definition exactly — mean "
        "allele frequency across callers ≥3%, with the strand-bias test applied to the iVar "
        "strand counts — and therefore reconciles with Table 2 by construction. \"Both callers "
        "(own thresholds)\" is stricter: each caller must independently report the variant at "
        "≥3% of its own allele frequency and pass a strand-bias test on its own strand counts.",
        "",
        panel_a.to_markdown(index=False),
        "",
        "The two columns diverge most at M2-31, where LoFreq reports far higher read depth "
        "than iVar (whose counts are base-quality filtered). Fisher's exact test gains power "
        "with depth, so a modest strand imbalance that is non-significant on iVar counts is "
        "significant on LoFreq counts. The primary analysis is therefore the more permissive "
        "of the two; sites where the columns differ should be read as having weaker "
        "strand-symmetry support.",
        "",
        "## Panel B. SA3 — stringent depth restriction (≥200× vs ≥100×)",
        "",
        wide("SA3").to_markdown(index=False),
        "",
        "Detection counts fall modestly under the stricter depth requirement because the "
        "denominator shrinks. No site changes qualitative status, and both HA receptor-binding "
        "domain sites remain at zero detections.",
        "",
        "## Panel C. SA4 — platform stratification",
        "",
        wide("SA4").to_markdown(index=False),
        "",
        "Every adaptation-site detection in the corpus arises from Illumina data; the Oxford "
        "Nanopore subset yields none. Because the Nanopore subset is small and contributes no "
        "detections, this analysis cannot test for a platform-by-host interaction and is "
        "reported as uninformative rather than as evidence of platform equivalence.",
        "",
        "## Panel D. SA5 — library-strategy stratification",
        "",
        wide("SA5").to_markdown(index=False),
        "",
        "All detections arise from WGS/RANDOM libraries. AMPLICON-tagged libraries make up "
        "roughly 1% of the corpus and contribute no detections, so primer-scheme artefacts "
        "cannot be assessed against a comparably powered WGS comparator. As with SA4, the "
        "absence of AMPLICON detections reflects the small subset size and is not evidence "
        "that library preparation has no effect.",
    ]

    out = MANUSCRIPT_DIR / "table_s5_sa2_sa5.md"
    out.write_text("\n".join(md))
    print(f"Wrote {out.relative_to(PROJECT_ROOT)}")
    print()
    print(panel_a.to_string(index=False))


if __name__ == "__main__":
    main()
